Add iceberg documentation
debrid/debrid-wiki pull request #12
Opened 2024-06-07 08:05 UTC by AyushSehrawat

2024-06-07 08:49 UTC, dreulavelle approved these changes

2024-06-14 17:51 UTC, dreulavelle requested changes
Dont forget to change all names to Riven

2024-06-16 01:56 UTC, AyushSehrawat commented
Will review today 👍🏻

2024-06-21 04:58 UTC, dreulavelle approved these changes

2024-06-21 04:58 UTC, dreulavelle commented on docs/riven/index.md
> +## Development
We shouldn't put development stuff here in this wiki. That should stay with the Riven repo

2024-06-21 04:59 UTC, dreulavelle commented on docs/riven/index.md
> +## Contributing
We can shorten a contributing section probably just to point people to the repo? Or get rid of it altogether

2024-06-21 04:59 UTC, dreulavelle commented on docs/riven/index.md
> +Rclone is mounted to /riven/vfs on your host machine -> settings should have: "host_mount": "/riven/vfs"
All the rclone/symlink stuff is incorrect

2024-06-21 05:15 UTC, AyushSehrawat commented on docs/riven/index.md
> +## Development
Okay!

2024-06-21 05:15 UTC, AyushSehrawat commented on docs/riven/index.md
> +## Contributing
Yea sure, that works too

2024-06-21 05:15 UTC, AyushSehrawat commented on docs/riven/index.md
> +Rclone is mounted to /riven/vfs on your host machine -> settings should have: "host_mount": "/riven/vfs"
Will see and edit accordingly

2024-06-21 05:16 UTC, AyushSehrawat commented on docs/riven/index.md
> +Rclone is mounted to /riven/vfs on your host machine -> settings should have: "host_mount": "/riven/vfs"
@davidemarcoli

2024-06-22 04:06 UTC, dreulavelle commented
I'm thinking to merge this pr so that I can open the project up in Obsidian and start working on the Riven docs. 

Is that alright? @davidemarcoli @AyushSehrawat

2024-06-22 07:14 UTC, davidemarcoli commented
@dreulavelle For me that's fine. I've not rewritten everything, so there may be some old stuff from the readme (for example the symlink stuff).

2024-06-22 07:22 UTC, AyushSehrawat commented
> I'm thinking to merge this pr so that I can open the project up in Obsidian and start working on the Riven docs.
> 
> Is that alright? @davidemarcoli @AyushSehrawat

You can do npm run docs:dev too

2024-06-22 07:22 UTC, merged